import {
    Activity,
    Apple,
    Archive,
    ArrowLeftRight,
    Award,
    Banknote,
    Bell,
    Bookmark,
    BookMarked,
    BookOpen,
    Boxes,
    Braces,
    BriefcaseBusiness,
    Cake,
    CalendarClock,
    CalendarDays,
    CalendarRange,
    Car,
    ChartPie,
    ChessKnight,
    Clapperboard,
    Clock,
    Cloud,
    Coins,
    Component,
    Compass,
    Contact,
    ContactRound,
    Container,
    Cpu,
    CreditCard,
    DatabaseBackup,
    Droplets,
    Dumbbell,
    FileSearch,
    FileStack,
    FileSpreadsheet,
    FileUser,
    FileWarning,
    FlaskConical,
    FolderArchive,
    FolderOpen,
    FolderSync,
    Gauge,
    Gift,
    GitFork,
    Globe,
    GraduationCap,
    Hammer,
    Handshake,
    HeartHandshake,
    History,
    KeyRound,
    Landmark,
    Layers,
    LayoutGrid,
    Lightbulb,
    Luggage,
    Mail,
    Map,
    Monitor,
    Moon,
    Music,
    NotebookPen,
    NotebookText,
    Package,
    PenLine,
    PiggyBank,
    Pill,
    Plug,
    Puzzle,
    QrCode,
    Receipt,
    Repeat,
    Rocket,
    Route,
    Scale,
    Send,
    Server,
    Shield,
    ShieldCheck,
    ShoppingCart,
    Sigma,
    Smartphone,
    Sprout,
    Stamp,
    Star,
    Stethoscope,
    Tags,
    Target,
    Terminal,
    Timer,
    TrendingUp,
    Wallet,
    Waypoints,
    Workflow,
    Wrench,
    Zap,
} from 'lucide-react';

export interface RoadmapItem {
    id: string;
    label: string;
    domain: string;
    icon: React.ReactNode;
}

export interface RoadmapGroup {
    id: string;
    label: string;
    icon: React.ReactNode;
    items: RoadmapItem[];
}

export const roadmapGroups: RoadmapGroup[] = [
    {
        id: 'kernel',
        label: 'Ecosystem Kernel',
        icon: <Layers size={18} />,
        items: [
            { id: '3', label: 'Notification Hub & Event Bus', domain: '03_NotificationHubAndEventBus', icon: <Bell size={15} /> },
            { id: '4', label: 'File & Document Vault', domain: '04_FileAndDocumentVault', icon: <FolderArchive size={15} /> },
            { id: '5', label: 'Unified Search Engine', domain: '05_UnifiedSearchEngine', icon: <FileSearch size={15} /> },
            { id: '6', label: 'Calendar & Scheduling Kernel', domain: '06_CalendarAndSchedulingKernel', icon: <CalendarDays size={15} /> },
            { id: '7', label: 'Contacts & Relationship Graph', domain: '07_ContactsAndRelationshipGraph', icon: <Contact size={15} /> },
            { id: '8', label: 'Tagging & Categorization Engine', domain: '08_TaggingAndCategorizationEngine', icon: <Tags size={15} /> },
            { id: '9', label: 'Audit Trail & Activity Timeline', domain: '09_AuditTrailAndActivityTimeline', icon: <History size={15} /> },
            { id: '10', label: 'Settings & Preferences Service', domain: '10_SettingsAndPreferencesService', icon: <KeyRound size={15} /> },
            { id: '11', label: 'Import/Export & Data Portability', domain: '11_ImportExportAndDataPortability', icon: <ArrowLeftRight size={15} /> },
            { id: '12', label: 'Dashboard & Widget Framework', domain: '12_DashboardAndWidgetFramework', icon: <LayoutGrid size={15} /> },
            { id: '13', label: 'UI Component Library & Theme System', domain: '13_UIComponentLibraryAndThemeSystem', icon: <Component size={15} /> },
            { id: '14', label: 'Plugin/Module Registry System', domain: '14_PluginAndModuleRegistrySystem', icon: <Puzzle size={15} /> },
            { id: '15', label: 'Offline Sync Engine', domain: '15_OfflineSyncEngine', icon: <Cloud size={15} /> },
        ],
    },
    {
        id: 'automation',
        label: 'Automation Core',
        icon: <Workflow size={18} />,
        items: [
            { id: '16', label: 'Rule Engine & Workflow Builder', domain: '16_RuleEngineAndWorkflowBuilder', icon: <Workflow size={15} /> },
            { id: '17', label: 'Scheduled Task & Cron Manager', domain: '17_ScheduledTaskAndCronManager', icon: <Timer size={15} /> },
            { id: '18', label: 'File Automation Watcher', domain: '18_FileAutomationWatcher', icon: <FolderSync size={15} /> },
        ],
    },
    {
        id: 'productivity',
        label: 'Productivity & Time',
        icon: <Clock size={18} />,
        items: [
            { id: '19', label: 'Unified Planner Engine', domain: '19_UnifiedPlannerEngine', icon: <CalendarRange size={15} /> },
            { id: '20', label: 'Goal Hierarchy & OKR Tracker', domain: '20_GoalHierarchyAndOKRTracker', icon: <Target size={15} /> },
            { id: '21', label: 'Time Audit & Time-Block Analyzer', domain: '21_TimeAuditAndTimeBlockAnalyzer', icon: <Timer size={15} /> },
            { id: '22', label: 'Personal Dashboard / Life OS Home', domain: '22_PersonalDashboardLifeOSHome', icon: <LayoutGrid size={15} /> },
            { id: '23', label: 'Work Shift & Schedule Manager', domain: '23_WorkShiftAndScheduleManager', icon: <CalendarClock size={15} /> },
            { id: '24', label: 'Project Roadmap Planner', domain: '24_ProjectRoadmapPlanner', icon: <Map size={15} /> },
            { id: '25', label: 'Productivity Insights Engine', domain: '25_ProductivityInsightsEngine', icon: <TrendingUp size={15} /> },
        ],
    },
    {
        id: 'knowledge',
        label: 'Knowledge & Learning',
        icon: <GraduationCap size={18} />,
        items: [
            { id: '26', label: 'Second Brain / Personal Wiki', domain: '26_SecondBrainPersonalWiki', icon: <BookOpen size={15} /> },
            { id: '27', label: 'Study & Course Tracker', domain: '27_StudyAndCourseTracker', icon: <GraduationCap size={15} /> },
            { id: '28', label: 'Certification & Skill Roadmap', domain: '28_CertificationAndSkillRoadmap', icon: <Award size={15} /> },
            { id: '29', label: 'Research & PDF Annotation Manager', domain: '29_ResearchAndPDFAnnotationManager', icon: <FileSearch size={15} /> },
            { id: '30', label: 'Flashcard Engine (SM-2)', domain: '30_FlashcardEngineSM2', icon: <BookMarked size={15} /> },
            { id: '31', label: 'Bookmark & Read-Later Archive', domain: '31_BookmarkAndReadLaterArchive', icon: <Bookmark size={15} /> },
            { id: '32', label: 'Code Snippet Manager', domain: '32_CodeSnippetManagerAndPackageIndex', icon: <Braces size={15} /> },
            { id: '33', label: 'Learning Analytics Dashboard', domain: '33_LearningAnalyticsDashboard', icon: <Gauge size={15} /> },
        ],
    },
    {
        id: 'organization',
        label: 'Personal Organization',
        icon: <FolderOpen size={18} />,
        items: [
            { id: '34', label: 'Document Archive & Version Vault', domain: '34_DocumentArchiveAndVersionVault', icon: <FolderOpen size={15} /> },
            { id: '35', label: 'Digital Media Library', domain: '35_DigitalMediaLibrary', icon: <Clapperboard size={15} /> },
            { id: '36', label: 'QR Asset Tagging System', domain: '36_QRAssetTaggingSystem', icon: <QrCode size={15} /> },
            { id: '37', label: 'Secrets, Password & 2FA Vault', domain: '37_SecretsPasswordAnd2FAVault', icon: <Shield size={15} /> },
            { id: '38', label: 'Subscription & Recurring Payment Tracker', domain: '38_SubscriptionAndRecurringPaymentTracker', icon: <CreditCard size={15} /> },
            { id: '39', label: 'Receipt & Warranty Archive', domain: '39_ReceiptAndWarrantyArchive', icon: <Receipt size={15} /> },
        ],
    },
    {
        id: 'goals',
        label: 'Goals, Habits & Self',
        icon: <Target size={18} />,
        items: [
            { id: '40', label: 'Habit Tracking Engine', domain: '40_HabitTrackingEngine', icon: <Repeat size={15} /> },
            { id: '41', label: 'Journal & Structured Review', domain: '41_JournalAndStructuredReviewSystem', icon: <NotebookPen size={15} /> },
            { id: '42', label: 'Decision Journal', domain: '42_DecisionJournal', icon: <Scale size={15} /> },
            { id: '43', label: 'Personal Scorecard / Life KPI', domain: '43_PersonalScorecardLifeKPITracker', icon: <Gauge size={15} /> },
            { id: '44', label: 'Vision Board & Bucket List', domain: '44_VisionBoardAndBucketListManager', icon: <Compass size={15} /> },
            { id: '45', label: 'Life Timeline & History Archive', domain: '45_LifeTimelineAndHistoryArchive', icon: <Waypoints size={15} /> },
        ],
    },
    {
        id: 'health',
        label: 'Health & Wellness',
        icon: <Activity size={18} />,
        items: [
            { id: '46', label: 'Workout & Training Planner', domain: '46_WorkoutAndTrainingPlanner', icon: <Dumbbell size={15} /> },
            { id: '47', label: 'Nutrition & Meal Planner', domain: '47_NutritionAndMealPlanner', icon: <Apple size={15} /> },
            { id: '48', label: 'Sleep & Recovery Tracker', domain: '48_SleepAndRecoveryTracker', icon: <Moon size={15} /> },
            { id: '49', label: 'Medication & Prescription Tracker', domain: '49_MedicationAndPrescriptionTracker', icon: <Pill size={15} /> },
            { id: '50', label: 'Medical History & Visit Log', domain: '50_MedicalHistoryAndVisitLog', icon: <Stethoscope size={15} /> },
            { id: '51', label: 'Symptom & Body Metrics Tracker', domain: '51_SymptomAndBodyMetricsTracker', icon: <Activity size={15} /> },
            { id: '52', label: 'Hydration & Movement Reminder', domain: '52_HydrationAndMovementReminderEngine', icon: <Droplets size={15} /> },
        ],
    },
    {
        id: 'finance',
        label: 'Finance',
        icon: <Wallet size={18} />,
        items: [
            { id: '53', label: 'Expense Tracking & Budgeting Engine', domain: '53_ExpenseTrackingAndBudgetingEngine', icon: <Wallet size={15} /> },
            { id: '54', label: 'Bill Payment & Reminder Engine', domain: '54_BillPaymentAndReminderEngine', icon: <CalendarClock size={15} /> },
            { id: '55', label: 'Savings & Financial Goal Planner', domain: '55_SavingsAndFinancialGoalPlanner', icon: <PiggyBank size={15} /> },
            { id: '56', label: 'Investment & Net Worth Tracker', domain: '56_InvestmentAndNetWorthTracker', icon: <Coins size={15} /> },
            { id: '57', label: 'Loan & Debt Payoff Planner', domain: '57_LoanAndDebtPayoffPlanner', icon: <Landmark size={15} /> },
            { id: '58', label: 'Insurance Policy Manager', domain: '58_InsurancePolicyManager', icon: <ShieldCheck size={15} /> },
            { id: '59', label: 'Tax Document Archive', domain: '59_TaxDocumentArchive', icon: <FileWarning size={15} /> },
            { id: '60', label: 'Purchase History & Price Tracker', domain: '60_PurchaseHistoryAndPriceTracker', icon: <ShoppingCart size={15} /> },
        ],
    },
    {
        id: 'home',
        label: 'Home & Property',
        icon: <Hammer size={18} />,
        items: [
            { id: '61', label: 'Home Maintenance Scheduler', domain: '61_HomeMaintenanceScheduler', icon: <Wrench size={15} /> },
            { id: '62', label: 'Home Improvement Project Planner', domain: '62_HomeImprovementProjectPlanner', icon: <Hammer size={15} /> },
            { id: '63', label: 'Appliance & Warranty Inventory', domain: '63_ApplianceAndWarrantyInventory', icon: <Plug size={15} /> },
            { id: '64', label: 'Utility Usage Tracker', domain: '64_UtilityUsageTracker', icon: <Zap size={15} /> },
            { id: '65', label: 'Garden & Plant Care Manager', domain: '65_GardenAndPlantCareManager', icon: <Sprout size={15} /> },
            { id: '66', label: 'Household Inventory Manager', domain: '66_HouseholdInventoryManager', icon: <Boxes size={15} /> },
        ],
    },
    {
        id: 'travel',
        label: 'Travel & Transport',
        icon: <Map size={18} />,
        items: [
            { id: '67', label: 'Trip Planner & Itinerary Builder', domain: '67_TripPlannerAndItineraryBuilder', icon: <Map size={15} /> },
            { id: '68', label: 'Travel Journal & Expense Tracker', domain: '68_TravelJournalAndExpenseTracker', icon: <Luggage size={15} /> },
            { id: '69', label: 'Visa & Travel Document Tracker', domain: '69_VisaAndTravelDocumentTracker', icon: <Stamp size={15} /> },
            { id: '70', label: 'Vehicle & Equipment Maintenance', domain: '70_VehicleAndEquipmentMaintenanceLog', icon: <Car size={15} /> },
            { id: '71', label: 'Personal Route Planner & Ride Log', domain: '71_PersonalRoutePlannerAndRideLog', icon: <Route size={15} /> },
        ],
    },
    {
        id: 'career',
        label: 'Career & Professional',
        icon: <BriefcaseBusiness size={18} />,
        items: [
            { id: '72', label: 'Resume & Portfolio Version Manager', domain: '72_ResumeAndPortfolioVersionManager', icon: <FileUser size={15} /> },
            { id: '73', label: 'Job Application & Interview Tracker', domain: '73_JobApplicationAndInterviewTracker', icon: <BriefcaseBusiness size={15} /> },
            { id: '74', label: 'Salary & Achievement Log', domain: '74_SalaryAndAchievementLog', icon: <Banknote size={15} /> },
            { id: '75', label: 'Meeting Notes & Action Items', domain: '75_MeetingNotesAndActionItemSystem', icon: <NotebookText size={15} /> },
        ],
    },
    {
        id: 'business',
        label: 'Business & Relationships',
        icon: <Handshake size={18} />,
        items: [
            { id: '76', label: 'Freelance Client & Invoice Tracker', domain: '76_FreelanceClientAndInvoiceTracker', icon: <Handshake size={15} /> },
            { id: '77', label: 'Personal CRM & Relationship Health', domain: '77_PersonalCRMAndRelationshipHealth', icon: <HeartHandshake size={15} /> },
            { id: '78', label: 'Email Follow-up Organizer', domain: '78_EmailFollowUpOrganizer', icon: <Mail size={15} /> },
            { id: '79', label: 'Template & Snippet Manager', domain: '79_TemplateAndSnippetManager', icon: <FileStack size={15} /> },
            { id: '80', label: 'Birthday & Important Dates Engine', domain: '80_BirthdayAnniversaryAndImportantDates', icon: <Cake size={15} /> },
            { id: '81', label: 'Gift Planner', domain: '81_GiftPlanner', icon: <Gift size={15} /> },
            { id: '82', label: 'Family Records & Emergency Vault', domain: '82_FamilyRecordsAndEmergencyInfoVault', icon: <ContactRound size={15} /> },
        ],
    },
    {
        id: 'entertainment',
        label: 'Entertainment & Lifestyle',
        icon: <Clapperboard size={18} />,
        items: [
            { id: '83', label: 'Unified Media Watch Tracker', domain: '83_UnifiedMediaWatchTracker', icon: <Clapperboard size={15} /> },
            { id: '84', label: 'Reading Tracker', domain: '84_ReadingTracker', icon: <BookMarked size={15} /> },
            { id: '85', label: 'Music & Podcast Library', domain: '85_MusicAndPodcastLibrary', icon: <Music size={15} /> },
            { id: '86', label: 'Chess Game Log & Repertoire', domain: '86_ChessGameLogAndRepertoireTracker', icon: <ChessKnight size={15} /> },
            { id: '87', label: 'Wishlist Manager', domain: '87_WishlistManager', icon: <Star size={15} /> },
        ],
    },
    {
        id: 'writing',
        label: 'Writing & Content',
        icon: <PenLine size={18} />,
        items: [
            { id: '88', label: 'Writing Project Tracker', domain: '88_WritingProjectTracker', icon: <PenLine size={15} /> },
            { id: '89', label: 'Blog & Content Publishing', domain: '89_BlogAndContentPublishingManager', icon: <Send size={15} /> },
            { id: '90', label: 'Idea Inbox & Development Pipeline', domain: '90_IdeaInboxAndDevelopmentPipeline', icon: <Lightbulb size={15} /> },
        ],
    },
    {
        id: 'devtools',
        label: 'Developer Tools',
        icon: <Terminal size={18} />,
        items: [
            { id: '91', label: 'API Testing & Documentation Platform', domain: '91_APITestingAndDocumentationPlatform', icon: <FlaskConical size={15} /> },
            { id: '92', label: 'Project Scaffolding Generator', domain: '92_ProjectScaffoldingGenerator', icon: <Terminal size={15} /> },
            { id: '93', label: 'Database Schema Visualizer', domain: '93_DatabaseSchemaVisualizer', icon: <GitFork size={15} /> },
            { id: '94', label: 'Personal Package Registry', domain: '94_PersonalPackageRegistry', icon: <Package size={15} /> },
            { id: '95', label: 'Local Dev Environment Dashboard', domain: '95_LocalDevEnvironmentDashboard', icon: <Monitor size={15} /> },
        ],
    },
    {
        id: 'devops',
        label: 'DevOps & Infrastructure',
        icon: <Server size={18} />,
        items: [
            { id: '96', label: 'Deployment Manager', domain: '96_DeploymentManager', icon: <Rocket size={15} /> },
            { id: '97', label: 'Docker Container Dashboard', domain: '97_DockerEnvironmentAndContainerDashboard', icon: <Container size={15} /> },
            { id: '98', label: 'Server & Homelab Inventory', domain: '98_ServerAndHomelabInventory', icon: <Server size={15} /> },
            { id: '99', label: 'Server Monitoring Dashboard', domain: '99_ServerMonitoringDashboard', icon: <Cpu size={15} /> },
            { id: '100', label: 'Backup Manager & Scheduler', domain: '100_BackupManagerAndScheduler', icon: <DatabaseBackup size={15} /> },
            { id: '101', label: 'Domain & SSL Certificate Tracker', domain: '101_DomainAndSSLCertificateTracker', icon: <Globe size={15} /> },
        ],
    },
    {
        id: 'security',
        label: 'Security',
        icon: <ShieldCheck size={18} />,
        items: [
            { id: '102', label: 'Security Audit Dashboard', domain: '102_SecurityAuditDashboard', icon: <ShieldCheck size={15} /> },
            { id: '103', label: 'Device Inventory & Login History', domain: '103_DeviceInventoryAndLoginHistory', icon: <Smartphone size={15} /> },
        ],
    },
    {
        id: 'analytics',
        label: 'Analytics & Insights',
        icon: <ChartPie size={18} />,
        items: [
            { id: '104', label: 'Unified Analytics & KPI Dashboard', domain: '104_UnifiedAnalyticsAndKPIDashboard', icon: <ChartPie size={15} /> },
            { id: '105', label: 'Life Statistics Engine', domain: '105_LifeStatisticsEngine', icon: <Sigma size={15} /> },
            { id: '106', label: 'Custom Report Builder', domain: '106_CustomReportBuilder', icon: <FileSpreadsheet size={15} /> },
        ],
    },
];
